# Generated by Django 4.1.2 on 2024-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id_nav', models.AutoField(db_column='id_Nav', primary_key=True, serialize=False)),
                ('nombre_nav', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='idServicios', primary_key=True, serialize=False)),
                ('titulo_servicio', models.CharField(max_length=50)),
                ('descripcion_servicio', models.CharField(max_length=1000)),
                ('precio', models.CharField(max_length=45)),
            ],
        ),
    ]
