# Generated by Django 4.1.2 on 2024-07-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quienesomo',
            fields=[
                ('id_quienesomos', models.AutoField(db_column='idQuienesomos', primary_key=True, serialize=False)),
                ('titulo_quienesomos', models.CharField(max_length=50)),
                ('descripcion_quienesomos', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Quienes_somos',
            },
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(db_column='id_Servicios', primary_key=True, serialize=False),
        ),
    ]
