# Generated by Django 4.1.2 on 2024-07-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring', '0002_quienesomo_alter_servicio_id_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='url_nav',
            field=models.CharField(default='default_value', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nav',
            name='id_nav',
            field=models.AutoField(db_column='idNav', primary_key=True, serialize=False),
        ),
    ]
