# Generated by Django 4.1.2 on 2024-07-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring', '0003_nav_url_nav_alter_nav_id_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(db_column='idServicios', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='nav',
            table='Navs',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='Servicio',
        ),
    ]
